//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class charge
    {
        public int id { get; set; }
        public string number { get; set; }
        public string destination { get; set; }
        public int page { get; set; }
        public System.DateTime date { get; set; }
        public string ChargedBy { get; set; }
    }
}
